<?php
ini_set('max_execution_time', 120);
ini_set('memory_limit', '256M');
require_once __DIR__ . '/../../config/cors.php';
require_once __DIR__ . '/../../config/config.php';
require_once __DIR__ . '/../../config/db.php';
require_once __DIR__ . '/../../config/auth.php';
require_once __DIR__ . '/../../config/helpers.php';
require_once VENDOR_PATH . 'autoload.php';

$user  = requireAuth();
$db    = getDB();
$input = getInput();

$clientId   = sanitise($input['client_id'] ?? '');
$reportType = sanitise($input['report_type'] ?? 'daily_hygiene');
$dateFrom   = sanitise($input['date_from'] ?? date('Y-m-d', strtotime('-1 day')));
$dateTo     = sanitise($input['date_to'] ?? date('Y-m-d'));
$content    = $input['content'] ?? null; // pre-generated content from an action

if (!$clientId || !canAccessClient($user, $clientId)) {
    respond(false, null, 'Access denied', 403);
}

$stmt = $db->prepare("SELECT * FROM clients WHERE id = ?");
$stmt->execute([$clientId]);
$client = $stmt->fetch();
if (!$client) {
    respond(false, null, 'Client not found', 404);
}

// Build HTML content
if ($content) {
    // Convert Markdown to HTML (basic conversion)
    $html = nl2br(htmlspecialchars($content));
} else {
    // Generate summary from DB
    $stmt = $db->prepare(
        "SELECT sentiment, COUNT(*) as cnt FROM mentions
         WHERE client_id = ? AND collected_at BETWEEN ? AND ?
         GROUP BY sentiment"
    );
    $stmt->execute([$clientId, $dateFrom . ' 00:00:00', $dateTo . ' 23:59:59']);
    $sentiments = ['positive' => 0, 'negative' => 0, 'neutral' => 0];
    foreach ($stmt->fetchAll() as $row) {
        $sentiments[$row['sentiment']] = (int) $row['cnt'];
    }

    $stmt = $db->prepare(
        "SELECT * FROM alerts WHERE client_id = ? AND triggered_at BETWEEN ? AND ?
         ORDER BY severity, triggered_at DESC LIMIT 10"
    );
    $stmt->execute([$clientId, $dateFrom . ' 00:00:00', $dateTo . ' 23:59:59']);
    $alerts = $stmt->fetchAll();

    $stmt = $db->prepare(
        "SELECT content, platform, author_handle, sentiment, reach_estimate, summary_en
         FROM mentions WHERE client_id = ? AND collected_at BETWEEN ? AND ?
         AND (is_viral = 1 OR reach_estimate > 500000)
         ORDER BY reach_estimate DESC LIMIT 5"
    );
    $stmt->execute([$clientId, $dateFrom . ' 00:00:00', $dateTo . ' 23:59:59']);
    $topMentions = $stmt->fetchAll();

    $html = '<h1>NAZAR Intelligence Report</h1>';
    $html .= '<p><strong>Client:</strong> ' . htmlspecialchars($client['name']) . ' | ' . htmlspecialchars($client['role']) . ', ' . htmlspecialchars($client['party']) . '</p>';
    $html .= '<p><strong>Period:</strong> ' . $dateFrom . ' to ' . $dateTo . '</p>';
    $html .= '<hr>';

    $html .= '<h2>Sentiment Overview</h2><table border="1" cellpadding="6"><tr><th>Positive</th><th>Negative</th><th>Neutral</th></tr>';
    $html .= '<tr><td>' . $sentiments['positive'] . '</td><td>' . $sentiments['negative'] . '</td><td>' . $sentiments['neutral'] . '</td></tr></table>';

    if (!empty($alerts)) {
        $html .= '<h2>Alerts (' . count($alerts) . ')</h2><ul>';
        foreach ($alerts as $a) {
            $html .= '<li><strong>[' . strtoupper($a['severity']) . ']</strong> ' . htmlspecialchars($a['title']) . '</li>';
        }
        $html .= '</ul>';
    }

    if (!empty($topMentions)) {
        $html .= '<h2>Top Mentions by Reach</h2>';
        foreach ($topMentions as $m) {
            $html .= '<div style="border:1px solid #ccc;padding:10px;margin-bottom:10px;">';
            $html .= '<strong>' . htmlspecialchars($m['platform']) . '</strong> by ' . htmlspecialchars($m['author_handle']);
            $html .= ' | Reach: ' . number_format($m['reach_estimate']);
            $html .= ' | Sentiment: <span style="color:' . ($m['sentiment']==='positive'?'green':($m['sentiment']==='negative'?'red':'gray')) . '">' . $m['sentiment'] . '</span>';
            $html .= '<p>' . htmlspecialchars($m['summary_en'] ?: mb_substr($m['content'], 0, 200)) . '</p>';
            $html .= '</div>';
        }
    }

    $html .= '<p style="color:#888;font-size:11px;">Generated by NAZAR Political Intelligence Platform by Saptanga Labs LLP — ' . date('d M Y H:i') . '</p>';
}

// Generate PDF
try {
    $mpdf = new \Mpdf\Mpdf([
        'margin_left'   => 15,
        'margin_right'  => 15,
        'margin_top'    => 20,
        'margin_bottom' => 20,
        'font_size'     => 11,
    ]);

    $mpdf->SetTitle('NAZAR Report — ' . $client['name']);
    $mpdf->SetAuthor('Saptanga Labs LLP');
    $mpdf->WriteHTML($html);

    if (!is_dir(REPORTS_PATH)) {
        mkdir(REPORTS_PATH, 0755, true);
    }

    $fileName = 'nazar_' . preg_replace('/[^a-z0-9]/', '_', strtolower($client['name'])) . '_' . $dateFrom . '_' . date('His') . '.pdf';
    $filePath = REPORTS_PATH . $fileName;
    $mpdf->Output($filePath, 'F');

    // Store report record
    $reportId = generateUUID();
    $db->prepare(
        "INSERT INTO reports (id, client_id, report_type, date_from, date_to, file_name, status)
         VALUES (?, ?, ?, ?, ?, ?, 'completed')"
    )->execute([$reportId, $clientId, $reportType, $dateFrom, $dateTo, $fileName]);

    respond(true, [
        'report_id'    => $reportId,
        'file_name'    => $fileName,
        'download_url' => APP_URL . '/reports/files/' . $fileName,
    ]);

} catch (Exception $e) {
    respond(false, null, 'PDF generation failed: ' . $e->getMessage(), 500);
}
