import { useState, useEffect } from 'react'
import { X, Copy, CheckCheck, Loader2 } from 'lucide-react'
import api from '../api/client'
import clsx from 'clsx'

interface ActionModalProps {
  isOpen: boolean
  onClose: () => void
  actionType: string
  clientId: string
  context?: Record<string, any>
  title?: string
}

const actionLabels: Record<string, string> = {
  counter_brief:        'Counter Brief',
  rapid_response:       'Rapid Response Tweets',
  press_kit:            'Press Kit',
  outreach_message:     'Outreach Message',
  whatsapp_forward:     'WhatsApp Forward',
  keyword_blocking_list:'Keyword Blocking List',
  narrative_brief:      'Narrative Brief',
  individual_strategy:  'Individual Strategy',
  daily_report:         'Daily Report',
  weekly_digest:        'Weekly Digest',
}

export default function ActionModal({ isOpen, onClose, actionType, clientId, context = {}, title }: ActionModalProps) {
  const [loading, setLoading] = useState(false)
  const [output, setOutput] = useState<string | null>(null)
  const [error, setError] = useState<string | null>(null)
  const [copied, setCopied] = useState(false)

  useEffect(() => {
    if (!isOpen || !clientId || !actionType) return
    setOutput(null)
    setError(null)
    setLoading(true)

    api.post('/actions/trigger.php', { client_id: clientId, action_type: actionType, context })
      .then((r) => setOutput(r.data.data.output))
      .catch((e) => setError(e.response?.data?.error || 'Action failed'))
      .finally(() => setLoading(false))
  }, [isOpen, actionType, clientId])

  const handleCopy = () => {
    if (output) {
      navigator.clipboard.writeText(output)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    }
  }

  // Parse rapid_response JSON
  let tweets: any[] | null = null
  if (actionType === 'rapid_response' && output) {
    try { tweets = JSON.parse(output) } catch {}
  }

  // Parse keyword list JSON
  let keywords: any[] | null = null
  if (actionType === 'keyword_blocking_list' && output) {
    try { keywords = JSON.parse(output) } catch {}
  }

  if (!isOpen) return null

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
      <div className="absolute inset-0 bg-black/40 backdrop-blur-sm" onClick={onClose} />
      <div className="relative bg-white rounded-2xl shadow-2xl w-full max-w-2xl max-h-[85vh] flex flex-col">
        {/* Header */}
        <div className="flex items-center justify-between p-5 border-b border-border">
          <div>
            <h3 className="font-bold text-gray-900">{title || actionLabels[actionType] || actionType}</h3>
            <p className="text-xs text-gray-400 mt-0.5">Generated by NAZAR · Saptanga Labs</p>
          </div>
          <button onClick={onClose} className="p-1.5 hover:bg-gray-100 rounded-lg">
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Body */}
        <div className="flex-1 overflow-y-auto p-5">
          {loading && (
            <div className="flex flex-col items-center justify-center py-16 gap-3">
              <Loader2 className="w-8 h-8 text-navy animate-spin" />
              <p className="text-sm text-gray-500">NAZAR is generating your {actionLabels[actionType]}...</p>
            </div>
          )}

          {error && (
            <div className="bg-red-50 border border-red-200 rounded-xl p-4 text-sm text-negative">{error}</div>
          )}

          {output && !loading && (
            <>
              {tweets && (
                <div className="space-y-3">
                  {tweets.map((t: any, i: number) => (
                    <div key={i} className="border border-border rounded-xl p-4">
                      <div className="flex justify-between items-center mb-2">
                        <span className="text-xs font-medium text-gray-500 capitalize">{t.tone?.replace(/_/g, ' ')}</span>
                        <span className="text-xs text-gray-400">{t.character_count || t.text?.length} chars</span>
                      </div>
                      <p className="text-sm text-gray-800">{t.text}</p>
                    </div>
                  ))}
                </div>
              )}

              {keywords && (
                <div className="flex flex-wrap gap-1.5">
                  {keywords.map((k: any, i: number) => (
                    <span
                      key={i}
                      className={clsx(
                        'px-2 py-1 rounded text-xs font-medium',
                        k.severity === 'high' ? 'bg-red-100 text-negative' : 'bg-orange-50 text-orange-800'
                      )}
                      title={`${k.category} · ${k.language}`}
                    >
                      {k.keyword}
                    </span>
                  ))}
                </div>
              )}

              {!tweets && !keywords && (
                <div className="prose prose-sm max-w-none">
                  <pre className="whitespace-pre-wrap text-sm text-gray-800 font-sans leading-relaxed">{output}</pre>
                </div>
              )}
            </>
          )}
        </div>

        {/* Footer */}
        {output && !loading && (
          <div className="flex items-center justify-end gap-2 p-4 border-t border-border">
            <button onClick={handleCopy} className="flex items-center gap-2 btn-ghost">
              {copied ? <CheckCheck className="w-4 h-4 text-positive" /> : <Copy className="w-4 h-4" />}
              {copied ? 'Copied!' : 'Copy'}
            </button>
            <button onClick={onClose} className="btn-primary">Close</button>
          </div>
        )}
      </div>
    </div>
  )
}
